'use strict';

const $ = (s) => document.querySelector(s);
const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
const dist = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
const rnd = (a, b) => a + Math.random() * (b - a);
const STORAGE = 'echoValeSave.v1';
const SETTINGS = 'echoValeSettings.v1';

const DATA = {
  regions: [
    ['Silberhain', 0, 0, 1700, 1250, '#244438'], ['Bruchwald', 1700, 0, 1700, 1250, '#172822'],
    ['Kaldorf', 3400, 0, 1700, 1250, '#3a332c'], ['Echo-Sümpfe', 0, 1250, 1700, 1250, '#1d3a32'],
    ['Relay-Türme', 1700, 1250, 1700, 1250, '#263541'], ['Schwarzgrat-Pass', 3400, 1250, 1700, 1250, '#332f35'],
    ['Kernzitadelle', 1700, 2500, 1700, 1200, '#211b32']
  ],
  mainQuests: [
    'Erwache im Silberhain', 'Sprich mit Mara am Lichtbruch', 'Sammle dein erstes Echo-Fragment', 'Aktiviere die Brücke aus Erinnerung',
    'Erreiche Kaldorf, das Dorf ohne Stimmen', 'Finde Elias’ erste Erinnerung', 'Untersuche den Relay-Turm',
    'Entscheide über Korrins Energiequelle', 'Überquere den Schwarzgrat', 'Stelle dich dem Archivwächter', 'Entscheide über das letzte Signal'
  ],
  sideQuests: ['Der stumme Schmied','Die verlorene Laterne','Stimmen im Brunnen','Die Maschine mit Herz','Maras Geheimnis','Der letzte Brief von Elias','Kinder des Nebels','Der vergessene Checkpoint'],
  endings: {
    heal: ['Heilungs-Ende', 'Du heilst Echo Vale, rettest Mara und löst Vale aus dem Käfig, ohne die Erinnerung des Tals zu brechen.'],
    control: ['Kontroll-Ende', 'Du übernimmst das Echo-Netz. Das Tal überlebt — aber jede Stimme flüstert nun deinen Namen.'],
    sacrifice: ['Opfer-Ende', 'Du schließt das letzte Signal in deinem Echo-Core ein. Alle erinnern sich. Nur du wirst Legende.'],
    dark: ['Dunkles Ende', 'Egoistische Entscheidungen nähren das Signal. Echo Vale wacht auf — und die Welt vergisst.']
  }
};

class AudioSystem {
  constructor(game){ this.game = game; this.ctx = null; }
  init(){ if(!this.ctx) this.ctx = new (window.AudioContext || window.webkitAudioContext)(); }
  blip(type='ui'){ const s=this.game.settings; if(!s.uiSounds && type==='ui') return; this.init(); const g=this.ctx.createGain(), o=this.ctx.createOscillator(); const f={ui:520,quest:740,echo:280,hit:120,checkpoint:880,end:180}[type]||420; o.frequency.setValueAtTime(f,this.ctx.currentTime); o.type=type==='hit'?'sawtooth':'sine'; g.gain.value=(s.master/100)*(s.effects/100)*0.08; g.gain.exponentialRampToValueAtTime(0.001,this.ctx.currentTime+.22); o.connect(g).connect(this.ctx.destination); o.start(); o.stop(this.ctx.currentTime+.24); }
}

class Input {
  constructor(game){ this.game=game; this.keys=new Set(); this.mouse={x:0,y:0,down:false,right:false}; window.addEventListener('keydown',e=>this.key(e,true)); window.addEventListener('keyup',e=>this.key(e,false)); window.addEventListener('mousemove',e=>{this.mouse.x=e.clientX;this.mouse.y=e.clientY}); window.addEventListener('mousedown',e=>{ if(e.button===2) this.game.useEcho(); else this.game.attack(); }); window.addEventListener('contextmenu',e=>e.preventDefault()); }
  key(e,on){ const k=e.key.toLowerCase(); if(on) this.keys.add(k); else this.keys.delete(k); if(!on) return; if([' ','tab','arrowup','arrowdown','arrowleft','arrowright'].includes(k)) e.preventDefault(); const g=this.game; if(k==='escape'||k==='tab') g.togglePause(); if(k==='e') g.interact(); if(k==='q') g.useEcho(); if(k==='f') g.attack(); if(k===' ') g.player.dodge(); if(k==='m') g.ui.openPanel('map'); if(k==='j') g.ui.openPanel('quests'); if(k==='i') g.ui.openPanel('inventory'); if(k>='1'&&k<='3') g.dialogue.choose(+k-1); if(k==='enter') g.dialogue.choose(0); }
  axis(){ return {x:(this.keys.has('d')||this.keys.has('arrowright'))-(this.keys.has('a')||this.keys.has('arrowleft')), y:(this.keys.has('s')||this.keys.has('arrowdown'))-(this.keys.has('w')||this.keys.has('arrowup')), sprint:this.keys.has('shift')}; }
}

class Player {
  constructor(game){ this.game=game; Object.assign(this,{x:520,y:520,r:18,hp:100,sta:100,echo:80,fragments:0,kaldorf:0,inv:[],stats:{compassion:0,truth:0,control:0,trust:0,risk:0},dodgeT:0,attackT:0}); }
  update(dt){ const a=this.game.input.axis(); let sp=a.sprint&&this.sta>2?230:145; const len=Math.hypot(a.x,a.y)||1; const nx=this.x+a.x/len*sp*dt, ny=this.y+a.y/len*sp*dt; if((a.x||a.y)&&a.sprint) this.sta-=25*dt; else this.sta=clamp(this.sta+18*dt,0,100); if(!this.game.world.collides(nx, this.y, this.r)) this.x=nx; if(!this.game.world.collides(this.x, ny, this.r)) this.y=ny; this.echo=clamp(this.echo+7*dt,0,100); this.dodgeT=Math.max(0,this.dodgeT-dt); this.attackT=Math.max(0,this.attackT-dt); }
  dodge(){ if(this.sta<22||this.dodgeT) return; const a=this.game.input.axis(); const len=Math.hypot(a.x,a.y)||1; this.x+=a.x/len*82; this.y+=a.y/len*82; this.sta-=22; this.dodgeT=.45; this.game.audio.blip('echo'); this.game.particles.burst(this.x,this.y,'#e7fbff',18); this.game.tutorial('dodge'); }
}

class World {
  constructor(game){ this.game=game; this.w=5100; this.h=3700; this.objects=[]; this.collectibles=[]; this.npcs=[]; this.enemies=[]; this.checkpoints=[]; this.notes=[]; this.relics=[]; this.switches=[]; this.discovery=new Set(); this.build(); }
  build(){ const add=(arr,o)=>arr.push(o); DATA.regions.forEach((r,i)=>{ for(let n=0;n<28;n++) add(this.objects,{type:n%5?'tree':'rock',x:rnd(r[1]+80,r[1]+r[3]-80),y:rnd(r[2]+80,r[2]+r[4]-80),r:rnd(22,48),region:r[0]}); });
    [[760,565,'Silberhain'],[2250,620,'Bruchwald'],[3920,630,'Kaldorf'],[820,1850,'Echo-Sümpfe'],[2500,1830,'Relay-Türme'],[4100,1880,'Schwarzgrat-Pass'],[2550,3020,'Kernzitadelle']].forEach((c,i)=>add(this.checkpoints,{id:'cp'+i,x:c[0],y:c[1],name:c[2],active:i===0,r:34}));
    [['Mara',650,510,'mara'],['Korrin',3900,720,'korrin'],['Elias-Echo',2440,1710,'elias'],['Archivwächter',2550,2940,'archiv'],['Stummer Schmied',3730,850,'smith'],['Nebelkind',970,1900,'child'],['Herzmaschine',2630,1880,'machine'],['Laternenhüterin',2220,650,'lantern']].forEach(n=>add(this.npcs,{name:n[0],x:n[1],y:n[2],id:n[3],r:24,wander:rnd(0,9)}));
    ['Schattenläufer','Rostwächter','Echo-Wolf','Relay-Drohne','Verderbter Hüter'].forEach((t,i)=>{ for(let n=0;n<4;n++) add(this.enemies,{type:t,x:1750+i*680+rnd(0,400),y:520+(n%2)*960+rnd(0,260),r:20+i*3,hp:35+i*25,max:35+i*25,stun:0}); });
    for(let i=0;i<12;i++) add(this.collectibles,{id:'frag'+i,kind:'fragment',x:520+(i%4)*920+rnd(0,260),y:540+Math.floor(i/4)*930+rnd(0,260),r:15,taken:false});
    for(let i=0;i<10;i++) add(this.notes,{id:'note'+i,kind:'note',x:900+(i%5)*780,y:350+Math.floor(i/5)*1600+rnd(0,420),r:14,taken:false,text:'Elias Notiz '+(i+1)+': Das Signal ist kein Feind. Es ist ein Hunger nach Bedeutung.'});
    for(let i=0;i<5;i++) add(this.relics,{id:'relic'+i,kind:'relic',x:1250+i*760,y:1020+(i%2)*1420,r:16,taken:false});
    [[980,610,0],[2160,1510,1],[2580,1510,2],[2850,1510,3]].forEach(s=>add(this.switches,{x:s[0],y:s[1],order:s[2],on:false,r:22})); }
  regionAt(x,y){ return DATA.regions.find(r=>x>=r[1]&&y>=r[2]&&x<r[1]+r[3]&&y<r[2]+r[4])||DATA.regions[0]; }
  collides(x,y,r){ if(x<25||y<25||x>this.w-25||y>this.h-25) return true; return this.objects.some(o=>dist({x,y},o)<o.r+r*.72); }
  update(dt){ this.discovery.add(this.regionAt(this.game.player.x,this.game.player.y)[0]); this.npcs.forEach(n=>{ n.wander+=dt; n.x+=Math.cos(n.wander)*6*dt; n.y+=Math.sin(n.wander*.7)*6*dt; }); this.enemies.forEach(e=>this.updateEnemy(e,dt)); }
  updateEnemy(e,dt){ if(e.hp<=0) return; e.stun=Math.max(0,e.stun-dt); const p=this.game.player, d=dist(e,p); if(d<330&&!e.stun){ const sp=e.type==='Echo-Wolf'?95:e.type==='Rostwächter'?42:65; e.x+=(p.x-e.x)/d*sp*dt; e.y+=(p.y-e.y)/d*sp*dt; if(d<e.r+p.r+5 && !p.dodgeT){ p.hp=clamp(p.hp-18*dt,0,100); if(p.hp<=0) this.game.respawn(); } } }
}

class Particles { constructor(game){this.game=game;this.items=[]} burst(x,y,c,n=10){ for(let i=0;i<n;i++) this.items.push({x,y,vx:rnd(-80,80),vy:rnd(-80,80),life:rnd(.35,1),c}); } update(dt){ const max={Niedrig:80,Mittel:160,Hoch:280}[this.game.settings.particles]; this.items=this.items.filter(p=>(p.life-=dt)>0).slice(-max); this.items.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt}); } }
class SeasonSystem { constructor(){this.t=0;this.list=['Frühling','Sommer','Herbst','Winter'];} update(dt){this.t+=dt*.025} get name(){return this.list[Math.floor(this.t)%4]} get day(){return ['Morgen','Mittag','Abend','Nacht'][Math.floor(this.t*4)%4]} }
class WeatherSystem { constructor(game){this.game=game;this.t=0;this.types=['klar','Nebel','leichter Regen','Sturm','Schnee','Echo-Sturm']} update(dt){this.t+=dt*.04} get type(){ const ch=this.game.quest.chapter>=5?5:Math.floor(this.t)%5; return this.types[ch]; } }

class QuestSystem {
  constructor(game){ this.game=game; this.main=0; this.chapter=1; this.side=DATA.sideQuests.map((n,i)=>({name:n,status:i<3?'aktiv':'unentdeckt',reward:['Fragment','Relikt','Ruf'][i%3]})); }
  advance(){ if(this.main<DATA.mainQuests.length-1){ this.main++; this.chapter=clamp(Math.floor(this.main/2)+1,1,5); this.game.toast('Quest aktualisiert: '+DATA.mainQuests[this.main]); this.game.audio.blip('quest'); this.game.save.auto(); } }
  completeSide(i,choice='mitfühlend'){ const q=this.side[i]; if(!q||q.status==='abgeschlossen') return; q.status='abgeschlossen'; this.game.player.fragments++; this.game.player.kaldorf+=choice==='hart'?-1:1; this.game.toast('Nebenquest abgeschlossen: '+q.name); this.game.save.auto(); }
}

class DialogueSystem {
  constructor(game){this.game=game;this.node=null}
  open(npc){ const lines={mara:['Mara','Du hörst es auch, oder? Dieses Summen unter der Erde. Es ist kein Wind. Es ist Erinnerung.'],korrin:['Korrin','Wenn ein Dorf seine Namen verliert, greift man nach jeder Maschine — auch nach einer gefährlichen.'],elias:['Elias','Ich habe das Signal nicht erschaffen. Ich habe es eingesperrt, weil es uns zu gut verstand.'],archiv:['Archivwächter','Vor dir liegen vier Türen: Heilung, Kontrolle, Opfer — und Hunger. Wähle, wer du geworden bist.'],smith:['Stummer Schmied','Er legt eine kalte Laterne in deine Hand. Darin klopft etwas wie ein Herz.'],child:['Nebelkind','Wir haben im Brunnen Stimmen versteckt. Bitte gib ihnen nicht Korrin.'],machine:['Herzmaschine','TAKT FEHLT. MITGEFÜHL ERKANNT. BEFEHL?'],lantern:['Laternenhüterin','Eine Laterne findet nicht den Weg. Sie entscheidet, welche Dunkelheit wahr sein darf.']}; const l=lines[npc.id]; this.node={npc,id:npc.id,name:l[0],text:l[1],choices:this.choices(npc.id)}; this.game.ui.render(); this.game.audio.blip('ui'); }
  choices(id){ if(id==='archiv') return [['Vale heilen',()=>this.game.end('heal')],['Echo-Netz kontrollieren',()=>this.game.end('control')],['Mich selbst opfern',()=>this.game.end('sacrifice')]]; return [['Mitgefühl zeigen',()=>this.apply({compassion:1,trust:1})],['Die Wahrheit fordern',()=>this.apply({truth:1,risk:1})],['Macht sichern',()=>this.apply({control:1,risk:1})]]; }
  apply(delta){ Object.entries(delta).forEach(([k,v])=>this.game.player.stats[k]+=v); if(this.game.quest.main<10) this.game.quest.advance(); this.close(); }
  choose(i){ if(!this.node) return; const c=this.node.choices[i]; if(c){ this.game.audio.blip('quest'); c[1](); } }
  close(){ this.node=null; this.game.ui.render(); }
}

class SaveSystem { constructor(game){this.game=game} data(){ const g=this.game,p=g.player; return {player:{x:p.x,y:p.y,hp:p.hp,fragments:p.fragments,stats:p.stats,inv:p.inv,kaldorf:p.kaldorf},quest:{main:g.quest.main,chapter:g.quest.chapter,side:g.quest.side},cp:g.world.checkpoints.map(c=>[c.id,c.active]),settings:g.settings,endings:g.endings,tutorial:g.tutorialDone}; } save(){ localStorage.setItem(STORAGE,JSON.stringify(this.data())); this.game.toast('Spiel gespeichert'); } auto(){ if(this.game.settings.autoSave) this.save(); } load(){ const d=JSON.parse(localStorage.getItem(STORAGE)||'null'); if(!d) return false; Object.assign(this.game.player,d.player); Object.assign(this.game.quest,d.quest); this.game.quest.side=d.quest.side; this.game.world.checkpoints.forEach(c=>{ const s=d.cp.find(x=>x[0]===c.id); if(s)c.active=s[1]; }); this.game.endings=d.endings||[]; this.game.tutorialDone=!!d.tutorial; return true; } reset(){ localStorage.removeItem(STORAGE); location.reload(); } }

class UI {
  constructor(game){this.game=game;this.app=$('#app');this.panel=null;this.tab='Grafik'}
  render(){ const g=this.game; document.documentElement.style.setProperty('--scale',g.settings.uiScale/100); if(g.state==='menu') return this.menu(); let h=`<div class="hud"><div class="bars glass"><b>Echo-Core</b><div class="bar"><i class="hp" style="width:${g.player.hp}%"></i></div><div class="bar"><i class="sta" style="width:${g.player.sta}%"></i></div><div class="bar"><i class="echo" style="width:${g.player.echo}%"></i></div><small>${g.season.name} · ${g.season.day} · ${g.weather.type}</small></div><div class="quest glass"><b>Kapitel ${g.quest.chapter}: ${DATA.mainQuests[g.quest.main]}</b><br><small>${g.hint}</small></div><canvas id="mini" class="minimap glass" width="190" height="190"></canvas></div>`; if(this.panel) h+=this.panelHtml(); if(g.dialogue.node) h+=this.dialogHtml(); this.app.innerHTML=h; this.bind(); this.drawMini(); }
  menu(){ const can=!!localStorage.getItem(STORAGE); this.app.innerHTML=`<div class="screen"><div class="menu glass"><div class="kicker">OPEN WORLD STORY RPG</div><h1 class="title">ECHO VALE<br>THE LAST SIGNAL</h1><p class="subtitle">Ein melancholisches 2.5D-Mystery-Abenteuer über Erinnerung, alte Technologie und die letzte Stimme unter dem Tal.</p><div class="stack"><button class="btn primary" data-act="new">Neues Spiel</button><button class="btn" data-act="continue" ${can?'':'disabled'}>Fortsetzen</button><button class="btn" data-panel="settings">Einstellungen</button><button class="btn" data-panel="controls">Steuerung</button><button class="btn" data-panel="credits">Credits</button></div></div></div>`; this.bind(); }
  panelHtml(){ const g=this.game; if(this.panel==='map') return `<div class="panel glass"><h2>Weltkarte</h2><canvas id="bigmap" width="900" height="520"></canvas><button class="btn" data-close>Schließen</button></div>`; if(this.panel==='quests') return `<div class="panel glass"><h2>Questlog</h2><div class="grid2"><div><h3>Hauptquest</h3>${DATA.mainQuests.map((q,i)=>`<div class="item">${i<g.quest.main?'✓':i===g.quest.main?'◆':'○'} ${q}</div>`).join('')}</div><div><h3>Nebenquests</h3>${g.quest.side.map(q=>`<div class="item"><b>${q.name}</b><br>${q.status} · Belohnung: ${q.reward}</div>`).join('')}</div></div><button class="btn" data-close>Schließen</button></div>`; if(this.panel==='inventory') return `<div class="panel glass"><h2>Inventar & Charakter</h2><div class="grid2"><div class="item">Echo-Fragmente: ${g.player.fragments}/12<br>Notizen/Relikte: ${g.player.inv.length}<br>Ruf in Kaldorf: ${g.player.kaldorf}</div><div class="item">${Object.entries(g.player.stats).map(([k,v])=>`${k}: ${v}`).join('<br>')}</div></div><button class="btn" data-close>Schließen</button></div>`; if(this.panel==='controls') return `<div class="panel glass"><h2>Steuerung</h2><p>WASD/Pfeile bewegen · Shift sprinten · Leertaste ausweichen · E interagieren · F/Linksklick Echo-Impuls · Q/Rechtsklick Echo-Core · M Karte · J Questlog · I Inventar · ESC/Tab Pause.</p><button class="btn" data-close>Schließen</button></div>`; if(this.panel==='credits') return `<div class="panel glass credits"><h2>Credits</h2><p>Design, Code, Story, prozedurale Grafik und WebAudio: lokal generiert. Keine externen Libraries, Bilder oder Audiodateien.</p><button class="btn" data-close>Schließen</button></div>`; return this.settingsHtml(); }
  settingsHtml(){ const s=this.game.settings,tabs=['Grafik','Audio','Gameplay','Steuerung','Speicher']; const row=(l,c)=>`<div class="setting"><span>${l}</span>${c}</div>`; let body=''; if(this.tab==='Grafik') body=row('Grafikqualität',this.sel('quality',['Niedrig','Mittel','Hoch']))+row('Partikelqualität',this.sel('particles',['Niedrig','Mittel','Hoch']))+row('Wettereffekte',this.chk('weatherFx'))+row('Jahreszeiten',this.chk('seasonFx'))+row('Screen Shake',this.chk('shake'))+row('Kameraweichheit',`<input data-set="cameraSmooth" type="range" min="5" max="20" value="${s.cameraSmooth}">`)+row('Kontrastmodus',this.chk('contrast'))+row('UI-Skalierung',`<input data-set="uiScale" type="range" min="80" max="125" value="${s.uiScale}">`); if(this.tab==='Audio') body=['master','music','effects','ambience'].map(k=>row(k,`<input data-set="${k}" type="range" min="0" max="100" value="${s[k]}">`)).join('')+row('UI-Sounds',this.chk('uiSounds')); if(this.tab==='Gameplay') body=row('Schwierigkeit',this.sel('difficulty',['Story','Normal','Hard']))+row('Auto-Save',this.chk('autoSave'))+row('Textgeschwindigkeit',`<input data-set="textSpeed" type="range" min="1" max="5" value="${s.textSpeed}">`)+row('Tutorial-Hinweise',this.chk('tutorialHints'))+row('Kamera-Zoom',`<input data-set="zoom" type="range" min="80" max="125" value="${s.zoom}">`)+row('Interaktionshilfe',this.chk('interactionHelp')); if(this.tab==='Steuerung') body='<p>Alle Tastatur- und Mausaktionen sind aktiv. Dialogoptionen zusätzlich mit 1/2/3 und Enter.</p>'; if(this.tab==='Speicher') body='<button class="btn" data-act="save">Speichern</button> <button class="btn" data-act="load">Laden</button> <button class="btn" data-act="checkpoint">Checkpoint laden</button> <button class="btn danger" data-act="reset">Save zurücksetzen</button>'; return `<div class="panel glass"><h2>Einstellungen</h2><div class="tabs">${tabs.map(t=>`<button class="btn" data-tab="${t}">${t}</button>`).join('')}</div>${body}<button class="btn" data-close>Schließen</button></div>`; }
  sel(k,a){return `<select data-set="${k}">${a.map(v=>`<option ${this.game.settings[k]===v?'selected':''}>${v}</option>`).join('')}</select>`} chk(k){return `<input data-set="${k}" type="checkbox" ${this.game.settings[k]?'checked':''}>`}
  dialogHtml(){ const d=this.game.dialogue.node; return `<div class="dialog glass"><div class="name">${d.name}</div><p>${d.text}</p>${d.choices.map((c,i)=>`<button class="btn choice" data-choice="${i}">${i+1}. ${c[0]}</button>`).join('')}</div>`; }
  bind(){ this.app.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>this.action(b.dataset.act)); this.app.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>this.openPanel(b.dataset.panel)); this.app.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{this.panel=null;this.game.state=this.game.prevState||'play';this.render()}); this.app.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.render()}); this.app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>this.game.dialogue.choose(+b.dataset.choice)); this.app.querySelectorAll('[data-set]').forEach(el=>el.oninput=()=>{ const v=el.type==='checkbox'?el.checked:el.type==='range'?+el.value:el.value; this.game.settings[el.dataset.set]=v; localStorage.setItem(SETTINGS,JSON.stringify(this.game.settings)); this.render(); }); }
  action(a){ if(a==='new') this.game.newGame(); if(a==='continue') this.game.continue(); if(a==='save') this.game.save.save(); if(a==='load') this.game.continue(); if(a==='reset') this.game.save.reset(); if(a==='checkpoint') this.game.loadCheckpoint(); }
  openPanel(p){ if(this.game.state==='menu'&&p==='settings'){} else {this.game.prevState=this.game.state; this.game.state='pause';} this.panel=p; this.render(); setTimeout(()=>this.drawBigMap(),0); }
  drawMini(){ const c=$('#mini'); if(!c) return; const x=c.getContext('2d'),g=this.game,p=g.player; x.clearRect(0,0,c.width,c.height); x.fillStyle='rgba(2,8,12,.45)'; x.fillRect(0,0,190,190); DATA.regions.forEach(r=>{x.fillStyle=g.world.discovery.has(r[0])?r[5]:'#111820';x.fillRect(r[1]/27,r[2]/20,r[3]/27,r[4]/20)}); x.fillStyle='#7df7ff'; x.beginPath(); x.arc(p.x/27,p.y/20,4,0,7); x.fill(); }
  drawBigMap(){ const c=$('#bigmap'); if(!c) return; const x=c.getContext('2d'),g=this.game; x.clearRect(0,0,900,520); DATA.regions.forEach(r=>{x.fillStyle=g.world.discovery.has(r[0])?r[5]:'#101820';x.fillRect(r[1]/5.8,r[2]/7.2,r[3]/5.8,r[4]/7.2);x.strokeStyle='rgba(255,255,255,.16)';x.strokeRect(r[1]/5.8,r[2]/7.2,r[3]/5.8,r[4]/7.2);x.fillStyle='#eef8ff';x.fillText(r[0],r[1]/5.8+14,r[2]/7.2+24)}); x.fillStyle='#7df7ff'; x.arc(g.player.x/5.8,g.player.y/7.2,7,0,7); x.fill(); }
}

class Game {
  constructor(){ this.canvas=$('#game'); this.ctx=this.canvas.getContext('2d'); this.settings=Object.assign({quality:'Hoch',particles:'Hoch',weatherFx:true,seasonFx:true,shake:true,cameraSmooth:12,contrast:false,uiScale:100,master:80,music:45,effects:75,ambience:55,uiSounds:true,difficulty:'Normal',autoSave:true,textSpeed:3,tutorialHints:true,zoom:100,interactionHelp:true},JSON.parse(localStorage.getItem(SETTINGS)||'{}')); this.audio=new AudioSystem(this); this.input=new Input(this); this.player=new Player(this); this.world=new World(this); this.particles=new Particles(this); this.season=new SeasonSystem(); this.weather=new WeatherSystem(this); this.quest=new QuestSystem(this); this.dialogue=new DialogueSystem(this); this.save=new SaveSystem(this); this.ui=new UI(this); this.camera={x:0,y:0}; this.state='menu'; this.prev=0; this.endings=[]; this.tutorialDone=false; this.hint='Beginne eine neue Reise.'; addEventListener('resize',()=>this.resize()); this.resize(); this.ui.render(); requestAnimationFrame(t=>this.loop(t)); }
  resize(){ this.canvas.width=innerWidth*devicePixelRatio; this.canvas.height=innerHeight*devicePixelRatio; this.ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0); }
  newGame(){ localStorage.removeItem(STORAGE); this.player=new Player(this); this.world=new World(this); this.quest=new QuestSystem(this); this.dialogue.close(); this.state='play'; this.hint='Sprich mit Mara. Bewege dich mit WASD oder Pfeiltasten.'; this.cinematic('Kapitel 1: Erwachen im Silberhain'); this.ui.render(); }
  continue(){ if(this.save.load()){ this.state='play'; this.toast('Savegame geladen'); } else this.newGame(); this.ui.render(); }
  togglePause(){ if(this.state==='menu') return; this.state=this.state==='pause'?'play':'pause'; this.ui.panel=this.state==='pause'?'settings':null; this.ui.render(); }
  tutorial(step){ if(this.tutorialDone||!this.settings.tutorialHints) return; const hints={dodge:'Gut. Weiche mit Leertaste aus, wenn ein Schatten springt.',echo:'Echo-Sicht enthüllt Brücken, Notizen und alte Maschinen.',attack:'Echo-Impuls ist Nahkampf — kein Schuss. Bleib in Reichweite.'}; this.hint=hints[step]||this.hint; }
  loop(t){ const dt=Math.min(.033,(t-this.prev)/1000||.016); this.prev=t; if(this.state==='play') this.update(dt); this.draw(t/1000); requestAnimationFrame(e=>this.loop(e)); }
  update(dt){ this.player.update(dt); this.world.update(dt); this.particles.update(dt); this.season.update(dt); this.weather.update(dt); const sm=this.settings.cameraSmooth; this.camera.x+=(this.player.x-innerWidth/2-this.camera.x)*dt*sm; this.camera.y+=(this.player.y-innerHeight/2-this.camera.y)*dt*sm; this.camera.x=clamp(this.camera.x,0,this.world.w-innerWidth); this.camera.y=clamp(this.camera.y,0,this.world.h-innerHeight); this.collect(); if(Math.random()<dt*3) this.particles.burst(this.player.x+rnd(-420,420),this.player.y+rnd(-300,300),this.weather.type==='Echo-Sturm'?'#b880ff':'#bffaff',1); }
  draw(time){ const c=this.ctx,p=this.player; c.clearRect(0,0,innerWidth,innerHeight); c.save(); c.translate(-this.camera.x,-this.camera.y); DATA.regions.forEach(r=>{ const grd=c.createLinearGradient(r[1],r[2],r[1]+r[3],r[2]+r[4]); grd.addColorStop(0,r[5]); grd.addColorStop(1,'#0c151b'); c.fillStyle=grd; c.fillRect(r[1],r[2],r[3],r[4]); }); this.drawPaths(c,time); [...this.world.collectibles,...this.world.notes,...this.world.relics].filter(o=>!o.taken).forEach(o=>this.drawGlow(c,o.x,o.y,o.kind==='fragment'?'#78f7ff':o.kind==='note'?'#ffd48a':'#c69bff',o.r,time)); this.world.switches.forEach(s=>this.drawGlow(c,s.x,s.y,s.on?'#8bffbd':'#65717a',s.r,time)); this.world.checkpoints.forEach(cp=>this.drawCheckpoint(c,cp,time)); this.world.objects.sort((a,b)=>a.y-b.y).forEach(o=>this.drawObject(c,o,time)); this.world.npcs.forEach(n=>this.drawNpc(c,n,time)); this.world.enemies.forEach(e=>e.hp>0&&this.drawEnemy(c,e)); this.drawPlayer(c,p,time); this.particles.items.forEach(q=>{c.globalAlpha=clamp(q.life,0,1); c.fillStyle=q.c; c.beginPath(); c.arc(q.x,q.y,3,0,7); c.fill(); c.globalAlpha=1}); c.restore(); this.drawAtmosphere(c,time); if(this.state==='play' && Math.floor(time*4)%4===0) this.ui.render(); }
  drawPaths(c,t){ c.strokeStyle='rgba(214,225,210,.15)'; c.lineWidth=42; c.lineCap='round'; c.beginPath(); c.moveTo(530,560); c.bezierCurveTo(1500,500,2450,790,3890,700); c.moveTo(760,590); c.bezierCurveTo(1050,1450,1900,1830,2550,1820); c.moveTo(2550,1820); c.bezierCurveTo(3500,1750,4080,1960,2550,3020); c.stroke(); }
  drawObject(c,o,t){ c.save(); c.translate(o.x,o.y); c.fillStyle='rgba(0,0,0,.28)'; c.beginPath(); c.ellipse(0,12,o.r,12,0,0,7); c.fill(); if(o.type==='tree'){ c.fillStyle='#162016'; c.fillRect(-5,-8,10,34); c.fillStyle=o.region==='Winter'?'#dcecff':'#244f38'; c.beginPath(); c.ellipse(Math.sin(t+o.x)*4,-22,o.r*.75,o.r,0,0,7); c.fill(); c.fillStyle='rgba(130,255,225,.16)'; c.beginPath(); c.arc(0,-24,o.r*.35,0,7); c.fill(); } else { c.fillStyle='#596066'; c.beginPath(); c.ellipse(0,0,o.r*.85,o.r*.55,-.3,0,7); c.fill(); } c.restore(); }
  drawGlow(c,x,y,col,r,t){ c.save(); c.shadowColor=col; c.shadowBlur=22; c.fillStyle=col; c.globalAlpha=.65+.25*Math.sin(t*4); c.beginPath(); c.arc(x,y,r,0,7); c.fill(); c.restore(); }
  drawCheckpoint(c,cp,t){ this.drawGlow(c,cp.x,cp.y,cp.active?'#7df7ff':'#566674',cp.r,t); c.fillStyle='#e8fbff'; c.fillRect(cp.x-6,cp.y-38,12,54); }
  drawNpc(c,n,t){ c.fillStyle='rgba(0,0,0,.3)'; c.beginPath(); c.ellipse(n.x,n.y+18,22,8,0,0,7); c.fill(); c.fillStyle=n.id==='mara'?'#d8ccff':n.id==='korrin'?'#ffbd8a':'#b9e7ff'; c.beginPath(); c.arc(n.x,n.y,18,0,7); c.fill(); c.fillStyle='#fff'; c.fillText(n.name,n.x-28,n.y-28); }
  drawEnemy(c,e){ c.fillStyle='rgba(0,0,0,.35)'; c.beginPath(); c.ellipse(e.x,e.y+16,e.r,9,0,0,7); c.fill(); c.fillStyle=e.type==='Rostwächter'?'#9d7053':e.type==='Relay-Drohne'?'#75a7b8':'#2a2232'; c.beginPath(); c.arc(e.x,e.y,e.r,0,7); c.fill(); c.strokeStyle='#ff6b7a'; c.strokeRect(e.x-18,e.y-e.r-14,36,4); c.fillStyle='#ff6b7a'; c.fillRect(e.x-18,e.y-e.r-14,36*(e.hp/e.max),4); }
  drawPlayer(c,p,t){ c.save(); c.translate(p.x,p.y); c.fillStyle='rgba(0,0,0,.35)'; c.beginPath(); c.ellipse(0,18,22,8,0,0,7); c.fill(); c.shadowColor='#7df7ff'; c.shadowBlur=p.dodgeT?34:14; c.fillStyle='#e9f7ff'; c.beginPath(); c.arc(0,0,p.r,0,7); c.fill(); c.fillStyle='#78f7ff'; c.beginPath(); c.arc(7,-4,6,0,7); c.fill(); c.restore(); }
  drawAtmosphere(c,t){ const season=this.settings.seasonFx?this.season.name:'Frühling', day=this.season.day; c.fillStyle={Frühling:'rgba(130,255,210,.04)',Sommer:'rgba(255,205,110,.07)',Herbst:'rgba(255,132,70,.08)',Winter:'rgba(190,220,255,.1)'}[season]; c.fillRect(0,0,innerWidth,innerHeight); if(day==='Nacht'){ c.fillStyle='rgba(0,8,20,.38)'; c.fillRect(0,0,innerWidth,innerHeight); } if(!this.settings.weatherFx) return; if(['Nebel','Echo-Sturm'].includes(this.weather.type)){ c.fillStyle=this.weather.type==='Echo-Sturm'?'rgba(130,80,255,.13)':'rgba(220,240,245,.12)'; for(let i=0;i<6;i++) c.fillRect(Math.sin(t*.25+i)*120-80,i*innerHeight/6,innerWidth+160,70); } if(['leichter Regen','Sturm','Schnee'].includes(this.weather.type)){ c.strokeStyle=this.weather.type==='Schnee'?'rgba(255,255,255,.65)':'rgba(155,210,255,.42)'; for(let i=0;i<90;i++){ const x=(i*97+t*180)%innerWidth,y=(i*53+t*330)%innerHeight; c.beginPath(); c.moveTo(x,y); c.lineTo(x+(this.weather.type==='Sturm'?22:4),y+(this.weather.type==='Schnee'?4:18)); c.stroke(); } } }
  collect(){ const all=[...this.world.collectibles,...this.world.notes,...this.world.relics]; all.forEach(o=>{ if(!o.taken&&dist(o,this.player)<42){ o.taken=true; if(o.kind==='fragment') this.player.fragments++; else this.player.inv.push(o.text||o.id); this.particles.burst(o.x,o.y,'#7df7ff',24); this.toast(o.kind==='fragment'?'Echo-Fragment gesammelt':'Lore gefunden'); this.tutorial('echo'); if(this.quest.main<3) this.quest.advance(); }}); }
  interact(){ const near=[...this.world.npcs,...this.world.checkpoints,...this.world.switches].filter(o=>dist(o,this.player)<90).sort((a,b)=>dist(a,this.player)-dist(b,this.player))[0]; if(!near) return this.toast('Nichts in Reichweite'); if(near.name&&near.id) return this.dialogue.open(near); if(near.id&&near.id.startsWith('cp')){ near.active=true; this.player.hp=100; this.toast('Signalstein aktiviert: '+near.name); this.audio.blip('checkpoint'); this.save.save(); if(this.quest.main<2) this.quest.advance(); return; } if('order' in near){ near.on=true; this.toast('Energiepfad '+(near.order+1)+' stabilisiert'); this.audio.blip('echo'); if(this.world.switches.every(s=>s.on)) { this.toast('Die Relay-Brücke erwacht.'); if(this.quest.main<4) this.quest.advance(); } } }
  useEcho(){ if(this.player.echo<18) return this.toast('Echo-Energie zu niedrig'); this.player.echo-=18; this.particles.burst(this.player.x,this.player.y,'#bda0ff',35); this.tutorial('echo'); this.audio.blip('echo'); this.world.enemies.forEach(e=>{ if(e.hp>0&&dist(e,this.player)<120){ e.stun=2; if(this.player.stats.compassion>1) e.hp-=10; }}); }
  attack(){ if(this.state!=='play'||this.player.attackT) return; this.player.attackT=.36; this.audio.blip('hit'); this.tutorial('attack'); this.world.enemies.forEach(e=>{ if(e.hp>0&&dist(e,this.player)<76){ e.hp-=28; e.stun=.55; this.particles.burst(e.x,e.y,'#ff6b7a',15); if(e.hp<=0){ this.player.echo=clamp(this.player.echo+18,0,100); if(this.quest.main<9&&this.world.regionAt(this.player.x,this.player.y)[0]!=='Silberhain') this.quest.advance(); } }}); }
  loadCheckpoint(){ const cp=[...this.world.checkpoints].reverse().find(c=>c.active)||this.world.checkpoints[0]; this.player.x=cp.x; this.player.y=cp.y; this.player.hp=100; this.state='play'; this.ui.panel=null; this.toast('Checkpoint geladen'); }
  respawn(){ this.toast('Du zerfällst in Echo — und kehrst zurück.'); this.loadCheckpoint(); }
  end(kind){ const s=this.player.stats; if(kind==='heal'&&s.compassion+s.trust<2) kind='dark'; if(kind==='control'&&s.control<1) kind='sacrifice'; this.endings=[...new Set([...this.endings,kind])]; this.state='pause'; this.ui.panel=null; this.save.save(); const e=DATA.endings[kind]; this.ui.app.innerHTML=`<div class="screen cinema"><div class="menu glass"><div class="kicker">FINALE FREIGESCHALTET</div><h1>${e[0]}</h1><p class="subtitle">${e[1]}</p><button class="btn primary" data-act="continue">Weiter erkunden</button><button class="btn" data-act="new">Neues Spiel</button></div></div>`; this.ui.bind(); this.audio.blip('end'); }
  cinematic(text){ this.toast(text); }
  toast(msg){ const el=$('#toast'); el.textContent=msg; el.classList.add('show'); clearTimeout(this.toastTimer); this.toastTimer=setTimeout(()=>el.classList.remove('show'),2600); }
}

window.addEventListener('DOMContentLoaded',()=>new Game());
